Oak Graph view
fsprojects/fantomas-tools pull request #478
Opened 2023-01-06 15:37 UTC by jindraivanek

Graph view for Oak tree.

![image](https://user-images.githubusercontent.com/34002/211044332-7c53984c-48d5-427d-b45d-e7c2bf12bd02.png)

Graph view can be enabled in settings, in Oak tab.

Rectangle nodes represents subtree, that was reduced to single node because of node limit.

Every node is clickable, then subtree from that node is viewed - back to upper level with "back" button.

TODO:
[ ] move "back" button to upper right corner

2023-01-06 16:07 UTC, jindraivanek commented
demo
![GraphView](https://user-images.githubusercontent.com/34002/211051042-d7e584d6-15a0-4492-ac66-605422aca1fb.gif)

2023-01-09 11:11 UTC, nojaf commented on src/client/fsharp/Oak/View.fs
> +    <| fun (model, dispatch: Msg -> unit) ->
Nitpick but please refactor all code that uses a `<|`.

2023-01-09 12:07 UTC, jindraivanek commented
added option for scaling size of nodes

2023-01-09 13:03 UTC, nojaf requested changes
First of amazing work! I'm really happy about this.

I must say I don't think the node structure is always correct:

When trying out:
```fsharp
module Tour.TuplesAndRecords

// From https://docs.microsoft.com/en-us/dotnet/fsharp/tour
// Visit the link above for more information on each topic
// You can also find more learning resources at https://fsharp.org/

module RecordTypes =

  /// This example shows how to define a new record type.
  type ContactCard =
    { Name: string;
      Phone: string;
      Verified: bool }

  /// This example shows how to instantiate a record type.
  let contact1 =
    { Name = "Alf";
      Phone = "(206) 555-0157";
      Verified = false }

  /// This example shows how to use "copy-and-update" on record values. It creates
  /// a new record value that is a copy of contact1, but has different values for
  /// the 'Phone' and 'Verified' fields.
  ///
  /// To learn more, see: https://docs.microsoft.com/dotnet/fsharp/language-reference/copy-and-update-record-expressions
  let contact2 =
    { contact1 with
        Phone = "(206) 555-0112";
        Verified = true }

  let ohSomeObjectExpression = { new System.Object() with member x.ToString() = "F#" }

  /// This example shows how to write a function that processes a record value.
  /// It converts a 'ContactCard' object to a string.
  let showContactCard (c: ContactCard) =
    c.Name
    + " Phone: "
    + c.Phone
    + (if not c.Verified then " (unverified)" else "")

  printfn "Alf's Contact Card: %s" (showContactCard contact1)
```

I got

![image](https://user-images.githubusercontent.com/2621499/211313531-3fc3b3a3-55c8-4b40-8115-4b77bdfb493f.png)

The `TypeDefnRecordNode` should not have bindings as children.

And this probably is a small parsing bug but truth be told the client shouldn't really be parsing this back to a tree structure. As the server had the tree at some point.

I'd be more in favour of changing the backend a bit to return the tree as JSON and take it from there.

If update the backend, would you be willing to update the client?

2023-01-09 13:53 UTC, nojaf commented on src/client/fsharp/Oak/View.fs
> +    let colors = {|
This is mind-blowingly clever to use an anonymous record at this location.
Pure genius 🤯

2023-01-09 14:02 UTC, jindraivanek commented
> First of amazing work! I'm really happy about this.

Thanks!

> And this probably is a small parsing bug 

Indeed, I found out it was easy (one-char :) ) fix, so I did it.

>but truth be told the client shouldn't really be parsing this back to a tree structure. As the server had the tree at some point.
> 
> I'd be more in favour of changing the backend a bit to return the tree as JSON and take it from there.
> 
> If update the backend, would you be willing to update the client?

But I agree, getting tree from server would be better and more robust. Will be happy to update client.

2023-01-09 16:06 UTC, nojaf commented on src/client/fsharp/Oak/View.fs
>          if model.Oak = Unchecked.defaultof<_> then
Feel free to change `model.Oak` to an option type if that makes things nicer.

2023-01-09 16:08 UTC, jindraivanek commented
@nojaf Updated to consume tree from server. Not sure if Oak result is 100% same as before, because it is reconstructed after tree process.

2023-01-09 17:55 UTC, nojaf commented
> Not sure if Oak result is 100% same as before, because it is reconstructed after tree process.

I'm afraid the outcome is still not correct indeed.

Would you mind extracting all the graph code to a separate file?
I don't think both views need to share any code.
For the default view, the JSON can just be transformed to `div`s as is.
That might be helpful in tracking down what is still going wrong.

Almost there!

2023-01-10 08:22 UTC, jindraivanek commented
Moved code related to GraphView to separate file. I compared graph with Oak results in that @nojaf example, and looks like it is correct. 

There is slight difference thought, Trivia nodes are connected as childrens to node where they are as `ContentBefore/After`  , but in Oak results it looks like they are siblings. We can make different style of edge (and maybe reverse direction of arrow) to represent Trivia connection, to avoid confusion.

2023-01-10 08:59 UTC, nojaf commented
I think it is correct now, one thing that still rubs me the wrong way is that the top-level node is not on top:

![image](https://user-images.githubusercontent.com/2621499/211504636-6ea25098-c496-4673-b981-82a06e54dd59.png)

I passed the level property as well for this:

![image](https://user-images.githubusercontent.com/2621499/211505305-ec1513a1-9935-4a6d-86cc-7a6b899028ad.png)

> There is slight difference thought, Trivia nodes are connected as childrens to node where they are as ContentBefore/After , but in Oak results it looks like they are siblings. We can make different style of edge (and maybe reverse direction of arrow) to represent Trivia connection, to avoid confusion.

Yes, good point. We could go all the way and implement our own [ctxRenderer](https://visjs.github.io/vis-network/docs/network/nodes.html). But that might be a stretch.
I think if we can create the trivia nodes as siblings nodes (with the same level property) and a different colour that might work.

2023-01-10 09:28 UTC, jindraivanek commented
> one thing that still rubs me the wrong way is that the top-level node is not on top:

Great, thanks.

> Yes, good point. We could go all the way and implement our own [ctxRenderer](https://visjs.github.io/vis-network/docs/network/nodes.html). But that might be a stretch. I think if we can create the trivia nodes as siblings nodes (with the same level property) and a different colour that might work.

I think that's not needed, we can change style of edge, I quickly did one option:
![image](https://user-images.githubusercontent.com/34002/211513056-e0eb3ad6-5e83-4db3-a8f7-a4c44cee10dd.png)
If you are in favor of this, I'll do it properly.
For other options of edge styles, see https://visjs.github.io/vis-network/docs/network/edges.html

2023-01-10 10:17 UTC, nojaf approved these changes
Wonderful! Big up @jindraivanek 🚀

2023-01-10 10:19 UTC, merged